/**
 * Auto Generated by LibragonExporter for TexturePacker
 **/

#include <libdragon.h>
#include <malloc.h>

typedef enum _game_ui_sprites {
	SPRITE_game_ui_A,
	SPRITE_game_ui_B,
	SPRITE_game_ui_C_D,
	SPRITE_game_ui_C_L,
	SPRITE_game_ui_C_R,
	SPRITE_game_ui_C_U,
	SPRITE_game_ui_HAND,
	SPRITE_game_ui_R,
	SPRITE_game_ui_START,
	SPRITE_game_ui_STICK,
	SPRITE_game_ui_Z,
	SPRITE_game_ui_gacha,
	SPRITE_game_ui_SPRITES_MAX
} game_ui_sprites;

#define alloc_and_load_spritesheet_game_ui(sprite)                                                 \
	{                                                                                              \
		int fp = dfs_open("/game_ui.sprite");                                                      \
		sprite = (sprite_t *)malloc(dfs_size(fp));                                                 \
		dfs_read(sprite, 1, dfs_size(fp), fp);                                                     \
		dfs_close(fp);                                                                             \
	}
